# Generated by Django 4.1.5 on 2023-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_article_description_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
