# Generated by Django 4.1.5 on 2023-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
